title: Johnathan Clementi 
logo: "/images/linkedinPhoto.jpg?raw=true" 
description: > 
  <i>Master of Urban Spatial Analytics, 2022</i><br>
  University of Pennsylvania<br><br>

  <i>Certificate, Geographic Information Systems, 2019</i><br>
  Pennsylvania State University<br><br>

  <i>B.S. Environmental Science and Policy, 2018</i><br>
  Marist College

theme: jekyll-theme-minimal
